name: Preview

on:
  pull_request:
    types: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Preview is building

      - name: Get modified demo path
        id: demo_path
        run: |
          curl -s -X GET -G "${{ github.event.pull_request.url }}/files" | node -p -e "JSON.parse(require('fs').readFileSync(0).toString()).map(file => file.filename).filter(name => name.startsWith('JSDemos/Demos/'))[0]?.split('/').slice(0, 4).join('/')"

      - name: Build
        run: |
          npm i
          mv JSDemos ..
          mv node_modules ..
        env:
          PR: ${{ github.event.number }}

      - name: Checkout to pages
        run: |
          git fetch --depth=1
          git checkout gh-pages 
          rm -rf $PR
          mkdir $PR
          mv ../JSDemos $PR
          mv ../node_modules $PR
        env:
          PR: ${{ github.event.number }}

      - name: Commit to pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: ${{ github.event.number }}
          branch: gh-pages
          commit_message: pr-${{ github.event.number }}-preview

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Don't forger to attach links to demos:
            Preview: https://${{ github.actor }}.github.io/${{ github.event.pull_request.repo.name }}/${{ github.event.number }}/JSDemos/Demos/<component>/<demo>/<framework>

            And don't forget to remind that mvc demos are not supported
