name: Preview

on:
  pull_request:
    types: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Preview is building

      - name: Get modified demo path
        id: demo_path
        run: |
          FILES = $(curl -s -X GET -G "${{ github.event.pull_request.url }}/files")
          NODE_SCRIPT = "JSON.parse(require('fs').readFileSync(0).toString()).map(file => file.filename).filter(name => name.startsWith('JSDemos/Demos/'))[0]?.split('/').slice(0, 4).join('/')"
          DEMO_PATH = $(echo $FILES | node -p -e $NODE_SCRIPT)
          echo "::set-output name=result::$DEMO_PATH"
      - name: Build
        run: |
          npm i
          mv JSDemos ..
          mv node_modules ..
        env:
          PR: ${{ github.event.number }}

      - name: Checkout to pages
        run: |
          git fetch --depth=1
          git checkout gh-pages 
          rm -rf $PR
          mkdir $PR
          mv ../JSDemos $PR
          mv ../node_modules $PR
        env:
          PR: ${{ github.event.number }}

      - name: Commit to pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: ${{ github.event.number }}
          branch: gh-pages
          commit_message: pr-${{ github.event.number }}-preview

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: |
            Preview: https://${{ github.actor }}.github.io/${{ github.event.repository.name }}/${{ github.event.number }}/${{ steps.demo_path.outputs.result }}/jQuery
